### ISSUE TITLE
Compatibility with angular 8.2.14

### ISSUE THREAD

**Issue by marxsk** [angular-slider/ngx-slider#174] opened 2020-02-24 14:11 UTC
After upgrade of angular to 8.2.14, we met the issue when using ng5-slider with range option. 

In our valueChange() function we are calling is the router.navigate(...). We are able to reproduce following situations:

1) click on high value, click elsewhere => okay
2) click on high value, use keyboard to move the bar => okay

3 - problem) drag high value to a new value. 'Navigation is triggered outside Angular zone'. So we have left Angular zone somewhere in the code. 

I would like to help with debugging this issue more but I need some pointers what to look for.

**Comment by piotrdz** [comment] 2020-11-06 10:00
I suggest to re-try with v2.0.0+. It might have been caused by rxjs version mismatch - the old version was still using rxjs 5, which may have been interacting negatively with rxjs 6+ used by Angular. v2.0.0 uses only rxjs 6+, so it should eliminate that possibility.

**Comment by piotrdz** [comment] 2022-02-13 09:01
Closing, assuming that v2.0.0+ works.

**Closed by piotrdz** 2022-02-13 09:01 UTC
Labels: need more information
