### ISSUE TITLE
Not working Dynamic options slider

### ISSUE THREAD

**Issue by winox** [angular-slider/ngx-slider#144] opened 2019-09-05 15:08 UTC
Not working Dynamic options slider for angular 8
example https://stackblitz.com/edit/ng5-slider-range-slider-dynamic-ceil-example-lndu3z

**Comment by winox** [comment] 2019-09-05 15:10
Not working Dynamic options slider for angular 8
example https://stackblitz.com/edit/ng5-slider-range-slider-dynamic-ceil-example-lndu3z

**Comment by philtyl** [comment] 2019-10-29 17:41
This seems to happen whenever options are being fed from a function instead of a property

example of both:  https://stackblitz.com/edit/ng5-slider-static-slider-bug

**Comment by winox** [comment] 2019-10-29 19:53
> This seems to happen whenever options are being fed from a function instead of a property
> 
> example of both: https://stackblitz.com/edit/ng5-slider-static-slider-bug

Here is the official example: https://stackblitz.com/edit/ng5-slider-range-slider-dynamic-ceil-example
I need this method for dynamically generating options, but on the 8th version of Angular it does not work

**Comment by winox** [comment] 2019-10-29 19:54
By the link https://angular-slider.github.io/ng5-slider/demos
also does not work on version 8

**Comment by winox** [comment] 2019-10-29 19:59
Actually, I need to show and hide labels dynamically

**Comment by piotrdz** [comment] 2020-10-29 10:51
Binding slider options to a function only works so long as Angular change detection doesn't get in the way.
In this case, unfortunately, it will get in the way.

Think about it this way:
1. You have an object of slider details called let's say `details`.
2. You move a slider handle.
3. Due to output bindings, the value of `details.value` and `details.highValue` changes.
4. Angular change detection kicks in since something in `details` has changed.
5. Angular will force the update to options object, since it is not smart enough to know what the `sliderOptions()` function is doing with `details`.
6. Slider will re-set itself with new options object.

Point 5. is a problem caused by over-eager change detection, which theoretically could be worked around.

However, point 6. is a known issue, which I am not going to fix. Change detection with inspecting the contents of options object would be a sure way to kill performance for little gain.

**Comment by piotrdz** [comment] 2020-11-04 09:36
This particular case of changing options is now fixed by changed in #111 and available in v2.0.1.

The dynamic sliders example is a good one to use, so I included it as a [demo on the official slider page](https://angular-slider.github.io/ngx-slider/demos#dynamically-created-sliders).

Closing.

**Closed by piotrdz** 2020-11-04 09:36 UTC
Labels: known issue
