### ISSUE TITLE
ERROR Error: Expecting instance of DOM Element

### ISSUE THREAD

**Issue by santosh2221994** [angular-slider/ngx-slider#179] opened 2020-04-01 15:55 UTC
'<ng5-slider [(value)]="value" [(highValue)]="highValue" [options]="options">
            </ng5-slider>'
'value: number = 40
  highValue: number = 60
  options: Options = {
    floor: 0,
    ceil: 100
  }'

**Comment by SpiegelSoft** [comment] 2020-06-17 16:23
Did you find the cause of this bug?

**Comment by Matthi0uw** [comment] 2020-07-31 07:51
Any solution ?

**Comment by shisho585** [comment] 2020-10-26 13:46
Maybe it's because you didn't put the end tag?

**Comment by piotrdz** [comment] 2020-10-31 20:05
I assume this is a duplicate of #195.

**Closed by piotrdz** 2020-10-31 20:05 UTC
Labels: duplicate
