### ISSUE TITLE
window reference in compatibility-helper.ts is breaking SSR

### ISSUE THREAD

**Issue by lowedown** [angular-slider/ngx-slider#311] opened 2022-02-24 14:05 UTC
There are window references in `src/ngx-slider/lib/compatibility-helper.ts` which break Server-Side rendering.
This could be fixed like this:

```
private static getWindow(): any {
  const win: Window = typeof window !== 'undefined' ? window : ({} as Window);
  return win;
}

public static isResizeObserverAvailable(): boolean {
    return getWindow().ResizeObserver !== undefined;
  }

public static isTouchEvent(event: any): boolean {
    if (getWindow().TouchEvent !== undefined) {
    ...
```

**Comment by piotrdz** [comment] 2024-02-15 07:20
Closing as duplicate of #66. SSR / Angular universal is not supported currently and is documented as a know issue.

**Closed by piotrdz** 2024-02-15 07:20 UTC
