### ISSUE TITLE
Using ng5-slider (Version 1.2.4) with Angular material dialog

### ISSUE THREAD

**Issue by faizu88** [angular-slider/ngx-slider#177] opened 2020-03-07 10:40 UTC
When the material dialog is opened, the slider incorrectly updates ceil.

Demo: https://stackblitz.com/edit/angular-material-range-slider-6gphpk

**Comment by piotrdz** [comment] 2020-11-07 01:55
Duplicate of #155.

**Closed by piotrdz** 2020-11-07 01:55 UTC
