### ISSUE TITLE
Slider with Ionic won't update

### ISSUE THREAD

**Issue by shifenis** [angular-slider/ngx-slider#321] opened 2022-05-18 14:56 UTC
Using the slider with the Ionic framework on the mobile device, the value is updated but the handler isn't updated.
I tried to stimulate the detection changes on the `valueChange` output.

Any idea about losing focus or anything like that?

**Comment by ThaddeeT** [comment] 2022-06-17 11:52
Hey man, https://github.com/angular-slider/ngx-slider/issues/256 !

Have a great day !

**Comment by piotrdz** [comment] 2024-02-15 07:23
Closing as duplicate of #256.

**Closed by piotrdz** 2024-02-15 07:23 UTC
