### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by AlexanderFSP** [angular-slider/ngx-slider#225] opened 2020-11-30 02:31 UTC
Server side slider initialization throws a TypeError due to call of DOM API method.

![image](https://user-images.githubusercontent.com/30397060/100562353-84f07380-32cc-11eb-824a-1e41efaa11e7.png)

**Comment by Parsa-Sedigh** [comment] 2020-12-14 07:40
I think you can use ifPlatformBrowser() to execute parts of code just in browser side. I'm using this package with angular 11.0.4 and universal and it has no problem

**Comment by floreauwe** [comment] 2021-05-06 06:16
Hi ! I have the same problem and already tried with ifPlatformBrowser()

`ERROR TypeError: this.elemRef.nativeElement.getBoundingClientRect is not a function
    at SliderHandleDirective.getBoundingClientRect (E:\sites\project-d\dist\server\main.js:149256:43)
    at SliderHandleDirective.calculateDimension (E:\sites\project-d\dist\server\main.js:149228:26)`

**Comment by eufelipemateus** [comment] 2023-04-02 05:59
Still have same problem here..

**Comment by piotrdz** [comment] 2024-02-15 07:02
Closing as duplicate of #66. Angular universal compatibility is a known issue.

**Closed by piotrdz** 2024-02-15 07:02 UTC

**Comment by techybolek** [comment] 2024-06-10 20:50
Angular 18.0.2, ngx-slider 17.0.2, same problem after trying to add SSR.
